id: fe797360-aee5-4d17-9f71-937b68d7b383
name: on-failure
jobs:
  - name: build
    steps:
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: notify
    steps:
      - name: alert
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: build
        condition:
          type: failed
          ref: build
    weight: 0
version: 1
