id: 43b680df-2166-4d31-909a-0191b9bf6143
name: on-failure
jobs:
  - name: build
    steps:
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: notify
    steps:
      - name: alert
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: build
        condition:
          type: failed
          ref: build
    weight: 0
version: 1
