id: 2b993ef8-2c73-48e1-bb35-7c7ba2998b69
name: parallel-steps
jobs:
  - name: job1
    steps:
      - name: step-a
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
      - name: step-b
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
      - name: step-c
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
