id: 97e6b381-0726-4f86-bece-539432c12797
name: parallel-steps
jobs:
  - name: job1
    steps:
      - name: step-a
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
      - name: step-b
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
      - name: step-c
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
