id: 97acf7da-54c5-4e65-99d1-3410a368ee28
name: diamond-deps
jobs:
  - name: job-a
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: job-b
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: job-c
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: job-a
        condition:
          type: succeeded
          ref: job-a
    weight: 0
  - name: job-d
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: job-a
        condition:
          type: succeeded
          ref: job-a
      - job: job-b
        condition:
          type: succeeded
          ref: job-b
    weight: 0
version: 1
