id: c8397878-1bdb-4649-bca0-76460d670d8c
name: on-failure
jobs:
  - name: build
    steps:
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: notify
    steps:
      - name: alert
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: build
        condition:
          type: failed
          ref: build
    weight: 0
version: 1
