id: 46966cbf-3b66-48e2-8750-df6d2733d3f4
name: simple-workflow
jobs:
  - name: job1
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args:
            - hello
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
