id: f5c09cb1-4396-4eb7-a838-f6a990d790cd
name: parallel-jobs
jobs:
  - name: job-a
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: job-b
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: job-c
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
