id: f27650da-2e93-4802-a563-e46d763122c3
name: simple-workflow
jobs:
  - name: job1
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args:
            - hello
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
