id: ec6f2239-a260-45b2-88d8-c5646cdc833b
name: parallel-steps
jobs:
  - name: job1
    steps:
      - name: step-a
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
      - name: step-b
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
      - name: step-c
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
