id: df99081d-68ac-4a66-9874-2dc3b8f6fdfb
name: parallel-jobs
jobs:
  - name: job-a
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: job-b
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: job-c
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
