id: f7fd6e6a-3837-4da6-a868-555f88468cfc
name: on-failure
jobs:
  - name: build
    steps:
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: notify
    steps:
      - name: alert
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: build
        condition:
          type: failed
          ref: build
    weight: 0
version: 1
