id: 30da137a-48c5-4071-89fc-fbe9a2b15f66
name: multi-job
jobs:
  - name: build
    steps:
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: test
    steps:
      - name: unit
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: build
        condition:
          type: succeeded
          ref: build
    weight: 0
version: 1
