id: 9a47801b-32fe-4f56-8070-d301b36ae8a8
name: simple-workflow
jobs:
  - name: job1
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args:
            - hello
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
