id: 1d68869e-1d90-4324-af6b-8df00ad3480e
name: parallel-jobs
jobs:
  - name: job-a
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: job-b
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: job-c
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
