id: 32759d22-1e83-47a6-8bf8-74625bd8e15a
name: on-failure
jobs:
  - name: build
    steps:
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: notify
    steps:
      - name: alert
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: build
        condition:
          type: failed
          ref: build
    weight: 0
version: 1
