id: 53bf59f6-91b7-408e-820a-c27bd3691815
name: step-deps
jobs:
  - name: build
    steps:
      - name: setup
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn:
          - step: setup
            condition:
              type: succeeded
              ref: setup
        weight: 0
    dependsOn: []
    weight: 0
version: 1
