id: cd74d0eb-5765-4fb9-9a9f-85a757e15076
name: step-deps
jobs:
  - name: build
    steps:
      - name: setup
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn:
          - step: setup
            condition:
              type: succeeded
              ref: setup
        weight: 0
    dependsOn: []
    weight: 0
version: 1
