id: b8b40220-dc34-4452-b254-128d8cf9da5b
name: simple-workflow
jobs:
  - name: job1
    steps:
      - name: step1
        task:
          type: shell
          command: echo
          args:
            - hello
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
