id: 3369f377-22fc-433c-a297-161202e247b7
name: conditional
jobs:
  - name: build
    steps:
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: test
    steps:
      - name: unit
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: build
        condition:
          type: succeeded
          ref: build
    weight: 0
version: 1
