id: 5deb7731-1ed6-42ed-8670-1f25c4ea0c30
name: conditional
jobs:
  - name: build
    steps:
      - name: compile
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
  - name: test
    steps:
      - name: unit
        task:
          type: shell
          command: echo
          args: []
        dependsOn: []
        weight: 0
    dependsOn:
      - job: build
        condition:
          type: succeeded
          ref: build
    weight: 0
version: 1
