// Swamp, an Automation Framework
// Copyright (C) 2026 System Initiative, Inc.
//
// This file is part of Swamp.
//
// Swamp is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3
// as published by the Free Software Foundation, with the Swamp
// Extension and Definition Exception (found in the "COPYING-EXCEPTION"
// file).
//
// Swamp is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Swamp.  If not, see <https://www.gnu.org/licenses/>.

import { getLogger } from "@logtape/logtape";
import { stripAnsiCode } from "@std/fmt/colors";
import { dirname, join, resolve } from "@std/path";
import * as zodModule from "zod";

const logger = getLogger(["swamp", "models", "bundle"]);

declare global {
  var __swamp_zod: typeof zodModule | undefined;
}

/**
 * Installs swamp's Zod module on globalThis so that extension bundles
 * with externalized `import { z } from "npm:zod@4"` (rewritten to
 * `const { z } = globalThis.__swamp_zod`) share the same Zod instance.
 *
 * This prevents dual-instance problems in the compiled binary where
 * `deno compile` resolves dynamic imports to a separate module instance.
 */
export function installZodGlobal(): void {
  if (!globalThis.__swamp_zod) {
    globalThis.__swamp_zod = zodModule;
    logger.debug`Installed Zod global (globalThis.__swamp_zod)`;
  }
}

/**
 * Rewrites externalized Zod imports in a bundle to reference `globalThis.__swamp_zod`.
 *
 * Handles:
 * - Named imports: `import { z } from "npm:zod@4"` → `const { z } = globalThis.__swamp_zod;`
 * - Aliased imports: `import { z as z2 } from "npm:zod"` → `const { z: z2 } = globalThis.__swamp_zod;`
 * - Star imports: `import * as zod from "npm:zod@4"` → `const zod = globalThis.__swamp_zod;`
 * - Already-rewritten lines are left untouched (idempotent).
 */
/**
 * Converts a Uint8Array to a base64 string without blowing the call stack.
 *
 * The naive `btoa(String.fromCharCode(...bytes))` spreads every byte onto
 * the call stack as a function argument, which causes `RangeError: Maximum
 * call stack size exceeded` for large bundles (e.g., extensions with inlined
 * npm packages like @octokit/rest or @slack/web-api).
 *
 * This function processes bytes in fixed-size chunks to stay well within
 * V8's call-stack limits regardless of bundle size.
 */
export function uint8ArrayToBase64(bytes: Uint8Array): string {
  const CHUNK_SIZE = 8192;
  let binary = "";
  for (let i = 0; i < bytes.length; i += CHUNK_SIZE) {
    const chunk = bytes.subarray(i, i + CHUNK_SIZE);
    binary += String.fromCharCode(...chunk);
  }
  return btoa(binary);
}

/**
 * Fixes CJS/ESM interop in bundles generated by `deno bundle` (esbuild).
 *
 * esbuild generates a `__toESM` helper that conditionally sets a `.default`
 * property on the wrapper object. When `--platform deno` is used, the
 * `isNodeMode` flag is false, so CJS modules that set `module.exports.__esModule = true`
 * (like tslib) don't get a `.default` property. Code that then destructures
 * `import_tslib.default` gets `undefined`, causing runtime crashes.
 *
 * This fix changes the `__toESM` helper to always set `.default`, which matches
 * the behavior of `--platform node` and is correct for Deno's Node compat layer.
 */
export function fixCjsEsmInterop(js: string): string {
  // Match the esbuild-generated __toESM ternary condition.
  // Original: `isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", ...) : target`
  // Fixed: always set .default (drop the `: target` fallback)
  return js.replace(
    /isNodeMode \|\| !mod \|\| !mod\.__esModule \? (__defProp\(target, "default", \{ value: mod, enumerable: true \}\)) : target/,
    "$1",
  );
}

/**
 * Truncates data URLs in error messages to avoid flooding the terminal
 * with megabytes of base64-encoded bundle content.
 */
export function sanitizeDataUrlError(error: unknown): string {
  const message = String(error);
  return message.replace(
    /data:application\/javascript;base64,[A-Za-z0-9+/=]{100,}/g,
    "data:application/javascript;base64,[truncated]",
  );
}

export function rewriteZodImports(js: string): string {
  // Match: import { ... } from "npm:zod...", "zod", or 'zod'
  // Handles both npm: prefixed specifiers (existing extensions) and
  // bare "zod" specifiers (when externalized via deno.json import map).
  // Only matches zod 4.x or unversioned — zod 3.x must NOT be rewritten
  // since globalThis.__swamp_zod provides zod 4.
  const namedImportPattern =
    /import\s*\{([^}]+)\}\s*from\s*["'](?:npm:)?zod(?:@4[^"']*)?["']\s*;?/g;
  js = js.replace(namedImportPattern, (_match, imports: string) => {
    // Convert `z as z2` to `z: z2` for destructuring syntax
    const destructured = imports
      .split(",")
      .map((s: string) => {
        const parts = s.trim().split(/\s+as\s+/);
        if (parts.length === 2) {
          return `${parts[0].trim()}: ${parts[1].trim()}`;
        }
        return parts[0].trim();
      })
      .filter((s: string) => s.length > 0)
      .join(", ");
    return `const { ${destructured} } = globalThis.__swamp_zod;`;
  });

  // Match: import * as <name> from "npm:zod..." or "zod"
  // Only matches zod 4.x or unversioned.
  const starImportPattern =
    /import\s*\*\s*as\s+(\w+)\s+from\s*["'](?:npm:)?zod(?:@4[^"']*)?["']\s*;?/g;
  js = js.replace(starImportPattern, (_match, name: string) => {
    return `const ${name} = globalThis.__swamp_zod;`;
  });

  return js;
}

/** Options for controlling bundle output. */
export interface BundleOptions {
  /**
   * When true, inline all dependencies (including zod) so the bundle is
   * fully self-contained — no network or shared module graph required.
   * Used for out-of-process execution (e.g., Docker containers).
   */
  selfContained?: boolean;

  /**
   * Absolute path to a deno.json project config. When provided, the bundler
   * uses `--config <path>` instead of `--no-lock`, so the project's import
   * map and lockfile govern dependency resolution.
   */
  denoConfigPath?: string;

  /**
   * Absolute path to a directory containing a package.json. When provided,
   * the bundler sets `cwd` on the subprocess so Deno auto-detects the
   * package.json and resolves bare specifiers from `node_modules/`.
   * Mutually exclusive with `denoConfigPath`.
   */
  packageJsonDir?: string;
}

/**
 * Checks whether a TypeScript source file contains bare specifier imports
 * (e.g., `from "zod"`, `from "@aws-sdk/..."`) that require a deno.json
 * import map to resolve. Returns true if any bare specifier is found.
 *
 * The bundler recognizes these import kinds; all but "bare" reach
 * `deno bundle` unchanged and are resolved by it without an import map:
 *
 * - relative (`./foo`, `../bar`) — resolved by path
 * - npm: (`npm:zod@4`) — non-local, resolved and inlined by deno bundle
 * - jsr: (`jsr:@std/assert@1`) — non-local, resolved and inlined by deno bundle
 * - https: (`https://deno.land/std/...`) — non-local, resolved and inlined by deno bundle
 * - node: (`node:fs`) — built-in, passed through unchanged
 * - bare (`zod`, `@aws-sdk/...`) — requires a deno.json or package.json to resolve
 *
 * Used by runtime loaders to determine whether a cached bundle should be
 * preferred over re-bundling when no deno.json is available (pulled
 * extensions with bare specifiers would always fail to rebundle locally).
 */
export function sourceHasBareSpecifiers(source: string): boolean {
  const importPattern = /(?:import|export)\s+[\s\S]*?from\s+["']([^"']+)["']/g;
  for (const match of source.matchAll(importPattern)) {
    const specifier = match[1];
    // Relative imports resolve by path — not bare.
    if (specifier.startsWith(".")) continue;
    // Non-local specifiers resolve without an import map — not bare.
    if (specifier.startsWith("npm:")) continue;
    if (specifier.startsWith("jsr:")) continue;
    if (specifier.startsWith("https:")) continue;
    if (specifier.startsWith("http:")) continue;
    // Node built-ins pass through unchanged — not bare.
    if (specifier.startsWith("node:")) continue;
    // Anything else is a bare specifier that needs an import map.
    return true;
  }
  return false;
}

/**
 * Determines whether a bundle failure is "expected" — i.e. a pulled extension
 * whose source contains bare specifiers but has no project config (deno.json /
 * deno.jsonc) to resolve them. In this case the failure is a known limitation,
 * not a user error, and the cached bundle should be used silently.
 *
 * Returns false (unexpected failure) when:
 * - A deno.json is available (bundling should have succeeded)
 * - The source has no bare specifiers (failure is not config-related)
 *
 * @param absolutePath - Absolute path to the source .ts file
 * @param repoDir - Repository root, used as the upward-search boundary
 */
export function isExpectedBundleFailure(
  absolutePath: string,
  repoDir?: string,
): boolean {
  // Walk up from the source file looking for deno.json / deno.jsonc.
  // If found, the project config should have resolved specifiers — failure
  // is unexpected.
  let dir = dirname(absolutePath);
  const root = resolve("/");
  while (dir !== root) {
    if (repoDir && resolve(dir) === resolve(repoDir)) break;
    for (const name of ["deno.json", "deno.jsonc"]) {
      try {
        Deno.statSync(join(dir, name));
        return false; // Config found — failure is unexpected
      } catch {
        // Not found — keep walking
      }
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  // No config found — check if source actually needs one.
  try {
    const source = Deno.readTextFileSync(absolutePath);
    return sourceHasBareSpecifiers(source);
  } catch {
    return false; // Can't read source — treat as unexpected
  }
}

/**
 * Reads a deno.json import map and determines how "zod" is mapped.
 * If it maps to a zod 4.x npm specifier, returns the resolved specifier
 * (e.g., "npm:zod@4.3.6") so it can be externalized alongside the
 * standard patterns. Returns undefined if there's no zod mapping or
 * if it maps to a non-4.x version (which should be inlined, not
 * externalized, since globalThis.__swamp_zod provides zod 4).
 */
async function resolveZodFromConfig(
  denoConfigPath: string,
): Promise<string | undefined> {
  try {
    const raw = await Deno.readTextFile(denoConfigPath);
    const config = JSON.parse(raw);
    const imports = config.imports as Record<string, string> | undefined;
    if (!imports || !imports["zod"]) return undefined;

    const target = imports["zod"];
    // Match npm:zod@4 or npm:zod@4.x.y — must start with major version 4
    if (/^npm:zod@4(?:\.|$)/.test(target)) return target;
    return undefined;
  } catch {
    return undefined;
  }
}

/**
 * Reads a package.json and checks whether zod is listed as a 4.x dependency.
 * Returns true if zod 4.x is found in dependencies or devDependencies.
 */
async function isZod4InPackageJson(
  packageJsonDir: string,
): Promise<boolean> {
  try {
    const raw = await Deno.readTextFile(join(packageJsonDir, "package.json"));
    const pkg = JSON.parse(raw);
    const deps: Record<string, string> = {
      ...pkg.dependencies,
      ...pkg.devDependencies,
    };
    const zodVersion = deps["zod"];
    if (!zodVersion) return false;
    // Match 4, 4.x.y, ^4, ~4, >=4, etc.
    return /^[\^~>=]*4(?:\.|$)/.test(zodVersion);
  } catch {
    return false;
  }
}

/**
 * Bundles a TypeScript extension file into JavaScript using `deno bundle` subprocess.
 *
 * Transpiles TypeScript syntax (interfaces, type annotations, generics) and
 * inlines all npm packages into the bundle. Only `zod` is externalized so that
 * extensions share the same zod instance as swamp (required for schema
 * `instanceof` checks). All other npm packages are resolved and inlined at
 * bundle time, which ensures they work in the compiled binary where only
 * swamp's own embedded dependency graph is available.
 *
 * When `options.selfContained` is true, zod is also inlined, producing a
 * bundle that needs no external modules at all. This is used for Docker
 * execution where the container has no access to swamp's module graph.
 *
 * @param absolutePath - Absolute filesystem path to the TypeScript file
 * @param denoPath - Absolute path to the deno binary to use for bundling
 * @param options - Optional bundle configuration
 * @returns Bundled JavaScript source code as a string
 */
export async function bundleExtension(
  absolutePath: string,
  denoPath: string,
  options?: BundleOptions,
): Promise<string> {
  logger.debug`Bundling extension: ${absolutePath}`;

  const tempFile = await Deno.makeTempFile({
    prefix: "swamp_bundle_",
    suffix: ".js",
  });

  try {
    // When using deno.json, pass --config so the import map governs resolution.
    // When using package.json, use --node-modules-dir=auto so Deno auto-detects
    // package.json via cwd and initializes node_modules/.deno/ if needed (this
    // makes it work with both `npm install` and `deno install`).
    // Otherwise, use --no-lock for the default no-project behavior.
    const args = options?.denoConfigPath
      ? ["bundle", "--config", options.denoConfigPath]
      : options?.packageJsonDir
      ? ["bundle", "--node-modules-dir=auto"]
      : ["bundle", "--no-lock", "--node-modules-dir=none"];

    // Externalize zod by default so in-process extensions share the
    // host's zod instance (required for `instanceof` schema checks).
    // Self-contained bundles inline everything for out-of-process use.
    if (!options?.selfContained) {
      args.push("--external", "npm:zod@4", "--external", "npm:zod");

      // Scan the source file for the exact zod specifier (e.g., npm:zod@4.3.6)
      // and externalize it too. The --external npm:zod@4 pattern only matches
      // exact "npm:zod@4", not fully-pinned versions like "npm:zod@4.3.6".
      const source = await Deno.readTextFile(absolutePath);
      const zodSpecMatch = source.match(
        /from\s*["'](npm:zod@4\.[^"']+)["']/,
      );
      if (zodSpecMatch) {
        args.push("--external", zodSpecMatch[1]);
      }

      // When using a deno.json import map, bare specifier "zod" is resolved
      // to the fully-qualified npm specifier (e.g., "npm:zod@4.3.6") before
      // esbuild sees it. Also externalize the resolved specifier and the
      // bare "zod" specifier. Only do this for zod 4.x — externalizing
      // zod 3.x would silently break since globalThis.__swamp_zod provides zod 4.
      if (options?.denoConfigPath) {
        const resolvedZod = await resolveZodFromConfig(options.denoConfigPath);
        if (resolvedZod) {
          args.push("--external", resolvedZod, "--external", "zod");
        }
      }

      // When using a package.json project, bare specifier "zod" needs to be
      // externalized. Check that the package.json lists zod 4.x before doing so.
      if (options?.packageJsonDir) {
        const isZod4 = await isZod4InPackageJson(options.packageJsonDir);
        if (isZod4) {
          args.push("--external", "zod");
        }
      }
    }

    args.push("--platform", "deno", "-o", tempFile, absolutePath);

    const command = new Deno.Command(denoPath, {
      args,
      stdout: "piped",
      stderr: "piped",
      // For package.json projects, set cwd so Deno auto-detects package.json
      // and resolves bare specifiers from node_modules/.
      ...(options?.packageJsonDir ? { cwd: options.packageJsonDir } : {}),
    });

    const output = await command.output();

    if (!output.success) {
      const stderr = new TextDecoder().decode(output.stderr);
      const stdout = new TextDecoder().decode(output.stdout);
      const rawDetails = (stderr + stdout).trim() ||
        "(no output — try running deno 2.7.x or later)";
      const details = stripAnsiCode(rawDetails);
      throw new Error(
        `deno bundle failed for ${absolutePath}: ${details}`,
      );
    }

    let js = await Deno.readTextFile(tempFile);

    if (!js) {
      // Type-only files (interfaces, type aliases) produce empty bundles
      // because TypeScript erases them at compile time. Return a minimal
      // module so the loader can silently skip it (no model/extension export).
      js = "export {};\n";
    }

    // Fix CJS/ESM interop for packages like tslib that set __esModule.
    js = fixCjsEsmInterop(js);

    // Rewrite externalized zod imports to use globalThis.__swamp_zod
    // so extensions share swamp's Zod instance in the compiled binary.
    if (!options?.selfContained) {
      js = rewriteZodImports(js);
    }

    logger.debug`Bundled ${absolutePath} (${js.length} bytes)`;
    return js;
  } finally {
    try {
      await Deno.remove(tempFile);
    } catch {
      // Temp file cleanup is best-effort
    }
  }
}
