/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is generated by scripts/generate_model_registry.ts
 * Run `deno task generate:models` to regenerate.
 *
 * Discovered 4 model(s):
 *   - ec2InstanceModel (aws/ec2/instance/ec2_instance_model.ts)
 *   - ec2SubnetModel (aws/ec2/subnet/ec2_subnet_model.ts)
 *   - ec2VpcModel (aws/ec2/vpc/ec2_vpc_model.ts)
 *   - echoModel (echo/echo_model.ts)
 */

import { type ModelDefinition, modelRegistry } from "./model.ts";

import { ec2InstanceModel } from "./aws/ec2/instance/ec2_instance_model.ts";
import { ec2SubnetModel } from "./aws/ec2/subnet/ec2_subnet_model.ts";
import { ec2VpcModel } from "./aws/ec2/vpc/ec2_vpc_model.ts";
import { echoModel } from "./echo/echo_model.ts";

/**
 * All discovered model definitions.
 */
const ALL_MODELS: ModelDefinition[] = [
  ec2InstanceModel,
  ec2SubnetModel,
  ec2VpcModel,
  echoModel,
];

/**
 * Registers all model definitions with the global registry.
 * Safe to call multiple times - will not re-register existing models.
 *
 * @returns Number of models registered
 */
export function initializeModelRegistry(): number {
  let registeredCount = 0;

  for (const model of ALL_MODELS) {
    if (!modelRegistry.has(model.type)) {
      modelRegistry.register(model);
      registeredCount++;
    }
  }

  return registeredCount;
}

// Track initialization state
let initialized = false;

/**
 * Ensures the model registry is initialized.
 * Safe to call multiple times - will only initialize once.
 *
 * @returns Promise resolving to number of models registered
 */
export function ensureModelRegistryInitialized(): Promise<number> {
  if (!initialized) {
    const count = initializeModelRegistry();
    initialized = true;
    return Promise.resolve(count);
  }
  return Promise.resolve(0);
}

/**
 * Returns the count of registered models.
 */
export function getRegisteredModelCount(): number {
  return ALL_MODELS.length;
}
