#!/usr/bin/env -S deno run --allow-read --allow-write
/**
 * Generates the model registry file by scanning for model definitions.
 *
 * This script runs at build time to discover all *_model.ts files and
 * generate static imports that Deno can bundle into compiled binaries.
 *
 * Usage:
 *   deno run --allow-read --allow-write scripts/generate_model_registry.ts
 *
 * Or via task:
 *   deno task generate:models
 */

import { walk } from "@std/fs/walk";
import { dirname, relative } from "@std/path";

const MODELS_DIR = new URL("../src/domain/models", import.meta.url).pathname;
const OUTPUT_FILE = new URL(
  "../src/domain/models/registry.generated.ts",
  import.meta.url,
).pathname;

interface DiscoveredModel {
  /** Relative import path from registry.generated.ts */
  importPath: string;
  /** Variable name for the import (e.g., ec2InstanceModel) */
  exportName: string;
  /** The file path for comments */
  filePath: string;
}

/**
 * Discovers all model files in the models directory.
 */
async function discoverModelFiles(): Promise<string[]> {
  const modelFiles: string[] = [];

  for await (
    const entry of walk(MODELS_DIR, {
      exts: [".ts"],
      match: [/_model\.ts$/],
      skip: [/_test\.ts$/, /registry\.generated\.ts$/],
    })
  ) {
    if (entry.isFile) {
      modelFiles.push(entry.path);
    }
  }

  return modelFiles.sort();
}

/**
 * Strips comments from TypeScript/JavaScript content.
 * Removes both single-line (//) and multi-line (/* *\/) comments.
 */
function stripComments(content: string): string {
  // Remove single-line comments
  const withoutSingleLine = content.replace(/\/\/.*$/gm, "");
  // Remove multi-line comments (including JSDoc)
  return withoutSingleLine.replace(/\/\*[\s\S]*?\*\//g, "");
}

/**
 * Extracts model export names from a file by parsing its content.
 * Looks for exports matching the pattern: export const xxxModel
 * Ignores commented-out code.
 */
async function extractModelExports(filePath: string): Promise<string[]> {
  const content = await Deno.readTextFile(filePath);
  // Strip comments to avoid matching commented-out exports
  const contentWithoutComments = stripComments(content);
  const exports: string[] = [];

  // Match: export const someNameModel = or export const someNameModel:
  // But NOT type exports or MODEL_TYPE constants
  const exportRegex = /export\s+const\s+(\w+Model)\s*[=:]/g;
  let match;

  while ((match = exportRegex.exec(contentWithoutComments)) !== null) {
    const name = match[1];
    // Skip MODEL_TYPE constants (e.g., EC2_INSTANCE_MODEL_TYPE)
    if (!name.includes("MODEL_TYPE") && !name.includes("_MODEL_")) {
      exports.push(name);
    }
  }

  return exports;
}

/**
 * Processes a model file and returns discovered model info.
 */
async function processModelFile(
  filePath: string,
): Promise<DiscoveredModel[]> {
  const exports = await extractModelExports(filePath);
  const relativePath = relative(dirname(OUTPUT_FILE), filePath);
  // Convert to ./ prefix and remove .ts extension for import
  const importPath = "./" + relativePath.replace(/\.ts$/, ".ts");

  return exports.map((exportName) => ({
    importPath,
    exportName,
    filePath: relative(MODELS_DIR, filePath),
  }));
}

/**
 * Generates the registry file content.
 */
function generateRegistryContent(models: DiscoveredModel[]): string {
  // Group imports by file
  const importsByFile = new Map<string, string[]>();
  for (const model of models) {
    const existing = importsByFile.get(model.importPath) || [];
    existing.push(model.exportName);
    importsByFile.set(model.importPath, existing);
  }

  // Generate import statements
  const imports: string[] = [];
  for (const [importPath, exportNames] of importsByFile) {
    imports.push(
      `import { ${exportNames.sort().join(", ")} } from "${importPath}";`,
    );
  }

  // Generate the file content
  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is generated by scripts/generate_model_registry.ts
 * Run \`deno task generate:models\` to regenerate.
 *
 * Discovered ${models.length} model(s):
${models.map((m) => ` *   - ${m.exportName} (${m.filePath})`).join("\n")}
 */

import { type ModelDefinition, modelRegistry } from "./model.ts";

${imports.sort().join("\n")}

/**
 * All discovered model definitions.
 */
const ALL_MODELS: ModelDefinition[] = [
${models.map((m) => `  ${m.exportName},`).join("\n")}
];

/**
 * Registers all model definitions with the global registry.
 * Safe to call multiple times - will not re-register existing models.
 *
 * @returns Number of models registered
 */
export function initializeModelRegistry(): number {
  let registeredCount = 0;

  for (const model of ALL_MODELS) {
    if (!modelRegistry.has(model.type)) {
      modelRegistry.register(model);
      registeredCount++;
    }
  }

  return registeredCount;
}

// Track initialization state
let initialized = false;

/**
 * Ensures the model registry is initialized.
 * Safe to call multiple times - will only initialize once.
 *
 * @returns Promise resolving to number of models registered
 */
export function ensureModelRegistryInitialized(): Promise<number> {
  if (!initialized) {
    const count = initializeModelRegistry();
    initialized = true;
    return Promise.resolve(count);
  }
  return Promise.resolve(0);
}

/**
 * Returns the count of registered models.
 */
export function getRegisteredModelCount(): number {
  return ALL_MODELS.length;
}
`;
}

// Main execution
async function main() {
  console.log("🔍 Scanning for model files...");

  const modelFiles = await discoverModelFiles();
  console.log(`   Found ${modelFiles.length} model file(s)`);

  const allModels: DiscoveredModel[] = [];

  for (const filePath of modelFiles) {
    const models = await processModelFile(filePath);
    allModels.push(...models);
  }

  console.log(`   Discovered ${allModels.length} model export(s):`);
  for (const model of allModels) {
    console.log(`     - ${model.exportName}`);
  }

  const content = generateRegistryContent(allModels);

  await Deno.writeTextFile(OUTPUT_FILE, content);
  console.log(`\n✅ Generated ${OUTPUT_FILE}`);
}

main();
